### ISSUE TITLE
Sudden resizing of splits when using user commands

### ISSUE THREAD

**Issue by RobertAudi** [roman/golden-ratio#16]
I have this user command in my `vimrc`:

```
command! -bang W w<bang>
```

When I use it, all the splits get resized. Even though the resizing of the current split is correct, it's annoying to have the other splits resized...

**Comment by idbrii** [comment]
Is this still a problem for you?

I don't see the problem as you describe:

```
edit hello
split
vert split
wincmd p
command! -bang W w<bang>
W
```
Nothing resizes.

However, if I manually resize a window (`vert resize 10`) and then `:write`, the tiny window gets bigger (20 width). Is that what you're describing?

My observed resize behavior occurs with `let g:golden_ratio_autocommand = 0` and `= 1`.

My observed resize behavior does not occur with `gvim +"source ~/.vim/bundle/sensible/plugin/sensible.vim" -Nu NONE hello` -- instead it resizes once you focus the tiny window (again 20 width). However, it occurs without golden-ratio installed.

Does it occur if you remove golden-ratio?

**Comment by idbrii** [comment]
Closed due to no response and no repro.
