### ISSUE TITLE
Always opens in right hand window when using FuzzyFinder

### ISSUE THREAD

**Issue by ukch** [roman/golden-ratio#21]
The below bug occurs when using golden-ratio in combination with [FuzzyFinder](https://bitbucket.org/ns9tks/vim-fuzzyfinder/).

To reproduce:
- Split the vim window into two panes using `:vsplit`
- Select the left-hand pane and use `:FufFile` to open a file.

Expected: The new buffer should open in the left-hand pane.
Actual: The new buffer opens in the right-hand pane.

This bug does not occur when opening files using `:e`, `:b` etc. nor does it occur when the golden-ratio plugin is disabled.

**Comment by idbrii** [comment]
Don't see any code that modifies splitbelow/right. I'd guess this is vim being smart with the size of your windows.

Can you try using these commands with Fuzzy finder: http://stackoverflow.com/a/6728687

Also, try changing the window you have active (try with left and with right).

Try disabling golden ratio in the Fuzzy finder buffer if it had one.

I'm assuming you're using the autocmd. Please try without it too.

**Comment by idbrii** [comment]
See #22 for how to disable for a buffer type.

**Comment by idbrii** [comment]
Closed due to no response.
