### ISSUE TITLE
Disable golden ratio for NERDtree

### ISSUE THREAD

**Issue by kirs** [roman/golden-ratio#22]
Thanks for a great Vim extension! I absolutely love it.

I'm wondering if it's possible to disable golden ratio in NERDtree.

Without golden ratio:

<img width="1234" alt="screen shot 2016-10-04 at 21 41 09" src="https://cloud.githubusercontent.com/assets/522155/19098464/5201dfe8-8a7b-11e6-8b0b-1fe4c86d0a77.png">

With golden ratio:

<img width="1234" alt="screen shot 2016-10-04 at 21 40 47" src="https://cloud.githubusercontent.com/assets/522155/19098458/4a95f4ec-8a7b-11e6-8099-247e724d5b5b.png">

cc @roman

**Comment by idbrii** [comment]
Try this (read more about it in help):

    let g:golden_ratio_exclude_nonmodifiable = 1

If that doesn't work, make an ftplugin for nerdtree with:

    let b:golden_ratio_resizing_ignored = 1

**Comment by vlada79** [comment]
Still does not work (neither of the options helped, NERDTree is resized both when it receives and when it looses focus). Please retest.

**Comment by erahhal** [comment]
@idbrii can you give details on how autocmd broke this and how you fixed it?  Thanks.

**Comment by idbrii** [comment]
@erahhal If you disable autocmd, then windows are only resized when you ask them to. So if NERDtree is embiggened, it's because you want it to be. Unfortunately, if it will be shrunk when another window is embiggened. I don't believe there's a way to prevent that (I believe b:golden_ratio_resizing_ignored only works on embiggening).

@vlada79 Focus NERDtree buffer and what do you get from `:echo b:golden_ratio_resizing_ignored ` ?

**Comment by poberherr** [comment]
@idbrii I did this 

> @vlada79 Focus NERDtree buffer and what do you get from :echo b:golden_ratio_resizing_ignored ?
 `0`

So my question is how to set it to `1` just for the nerdtree buffer?

**Comment by idbrii** [comment]
@poberherr I'm assuming you haven't written an ftplugin before. They're very simple!

When I said

> If that doesn't work, make an ftplugin for nerdtree with:

I meant:

Create a file in the special ftplugin directory:  

    :edit ~/.vim/ftplugin/nerdtree.vim

Add this line:

    let b:golden_ratio_resizing_ignored = 1

and save it!

Now when you open nerdtree, `:echo b:golden_ratio_resizing_ignored` should give you `1` 

The name of the file (nerdtree.vim) matches the 'filetype' setting in a nerdtree window. If you have other windows you don't want resized: Open window, type `:set filetype?` (the question mark tells vim to print the current value) and see the filetype name (for example, `netrw`). Use that name to create your ftplugin (`~/.vim/ftplugin/netrw.vim`).

Read more in `:help write-filetype-plugin`.

**Comment by poberherr** [comment]
@idbrii Many thanks. Indeed I didn't touch the `ftplugins` yet.
Since I use `nvim` and `Plug` it turned out to be:
`~/.config/nvim/ftplugin/nerdtree.vim`

Many thanks!

**Comment by tommyc38** [comment]
@idbrii Any idea why this solution doesn't work for me????
