### ISSUE TITLE
`set wrap` does not work in inactive window/pane/splits

### ISSUE THREAD

**Issue by ahillio** [roman/golden-ratio#24]
I have two files open in vertical splits. Each one is set to "wrap" and "linebreak" and it works fine for the split that's in focus, but only for that split. The non-focused split will not wrap lines at all.

When I switch from one split to the other, the newly focused-on split will wrap and linebreak successfully while the formerly in-focus (and now out-of-focus) split will cease wrapping lines.

Can a split that's not actively being worked in (not in focus, or whatever the terminology is) be configured to acknowledge the :set wrap setting?

Great little plugin btw, thanks :)

**Comment by idbrii** [comment]
golden-ratio automatically disables wrap in the nonfocused window. You can change it to enable wrap with this option:

     let g:golden_ratio_wrap_ignored = 1

There is currently no option to prevent 'wrap' from being modified.

**Comment by ahillio** [comment]
Oh great, thanks a lot!!!
