### ISSUE TITLE
feature-request: add support for a black list of buffer name patterns

### ISSUE THREAD

**Issue by free-easy** [roman/golden-ratio#29]
Hi,

I really like this plugin, as it removes the hassling necessity to continuously change window size.

However, in my specific case, I use [NERDTree](https://github.com/scrooloose/nerdtree) and [Tagbar](https://github.com/majutsushi/tagbar) and I want that only Tagbar (since symbols might be quite long) gets resized when it gains focus. I don't want NERDTree window to be affected by this plugin.

Thus I'm asking whether it could be possible a have a blacklist (array) of patterns (e.g. `NERD_tree_*`)
represeting buffer names. So buffers, whose name matches a item in the blacklist, are ignored by this plugin.

P.s. I've read of 
```vimscript
let g:golden_ratio_exclude_nonmodifiable = 1
```
but I only want one of the nonmodifiable buffers to be excluded.

**Comment by idbrii** [comment]
See [this comment](https://github.com/roman/golden-ratio/issues/22#issuecomment-267785637). The buffer variable is what you want in your ~/.vim/ftplugin/nerdtree.vim file. 

If that doesn't satisfy, checkout PR #15.
