### ISSUE TITLE
Ignore file management (NERDTree etc.) windows

### ISSUE THREAD

**Issue by dwierenga** [roman/golden-ratio#3]
You've got a really nice plugin. I've been looking for something like this for a while.

One thing I've noticed is that it automatically resizes the windows created by NERDTree (Vim Script 1658).  Normally you'd have a slim vertical NERDTree window alongside your main file.  Ideally you'd ignore sizing the NERDTree window and just size the window you're editing.

Same thing with the bufferlist plugin (Vim script 1325).

I'm not really a vim scripter, but I think what I'm really asking for is for buffers with a non-empty buftype (:help buftype) to be excluded from the automatic resizing.  Or maybe with just the buftype set to 'nofile' - I think it may be useful to have help buffers autoresized.

**Comment by aaronzirbes** [comment]
FYI: https://github.com/zhaocai/GoldenView.Vim seems to leave NerdTree alone, and seems to work with NeoVim as well

**Comment by ReneFroger** [comment]
Please switch to Golden Ratio and Evil (a very excellent Vim emulation, where your vimrc works) in Emacs.

**Comment by idbrii** [comment]
You can blacklist nonmodifiable easy and file types not too hard. See #22.

I only use golden ratio without autocmd, so I am not excited to support that use case (sorry @roman). I expect most people in this thread have moved in to solutions that focus on that use case? Closing.
