### ISSUE TITLE
quickfix window height should not exceed its number of lines

### ISSUE THREAD

**Issue by timfeirg** [roman/golden-ratio#30]
quickfix window can be resized by golden-ratio just like any other windows, if I didn't `let g:golden_ratio_exclude_nonmodifiable = 1`.

But resizing a quickfix window that contains 11 lines to fill 2/3 of the whole screen makes no sense, and causes waste of screen spaces. can we add some kind of constraint to quickfix windows so that the height do not exceed their number of lines?

![image](https://user-images.githubusercontent.com/4319104/42261798-e9809118-7f9b-11e8-8b67-20e5f05d1eec.png)

**Comment by idbrii** [comment]
A buffer-local variable (so it's not limited to one buffer type) to prevent sizing larger than the length sounds like an interesting idea.
