### ISSUE TITLE
E11: Invalid in command-line window; <CR> executes, CTRL-C quits

### ISSUE THREAD

**Issue by Shurakai** [roman/golden-ratio#36]
When using golden-ratio with my setup, I get this error:

> Error detected while processing function <SNR>51_resize_to_golden_ratio[17]..<SNR>51_resize_ignored_windows:                                                                               
> line    4:                                                                                                                                                                                 
> E11: Invalid in command-line window; <CR> executes, CTRL-C quits                                                                                                                           
> E11: Invalid in command-line window; <CR> executes, CTRL-C quits                                                                                                                           
> line    7:                                                                                                                                                                                 
> E11: Invalid in command-line window; <CR> executes, CTRL-C quits    

I commented out the corresponding lines (`exec window . "wincmd w`) and the error disappears, yet it still seems to work. (I only tested with a few splits.)

The loop seems to iterate over all windows, put the cursor in them, execute the command and then move back to the original window. I am not sure why it still works or why this error appears, but I am using the vim version in debian testing:

 VIM - Vi IMproved 8.1 (2018 May 18, compiled Mar 03 2020 16:41:00)                                                                                                                         
Included patches: 1-2269

Thanks!

**Comment by idbrii** [comment]
Can you reproduce this with `vim -Nu ~/.vim/reprovimrc.vim -U NONE` where `reprovimrc.vim` is:

```vim
" all plugins should work with sensible as a baseline.
let s:plugins = ['sensible']

" Plugins to test here ------------------------------------------
let s:plugins += ['golden-ratio']
" /end ----------------------------------------------------------

set runtimepath-=~/.vim
set runtimepath-=~/.vim/after
set runtimepath-=~/vimfiles
set runtimepath-=~/vimfiles/after
for plugin in s:plugins
    exec "set runtimepath^=~/.vim/bundle/". plugin
    exec "set runtimepath+=~/.vim/bundle/". plugin ."/after"
endfor
set viminfofile=NONE
```

**Comment by Shurakai** [comment]
I should have mentioned that I use the command-line window by default. So, adding 

```vim
" Map : to q: to use the command-line window by default
nnoremap : q:i
nnoremap q: :
```
to your config yields the error. (I've used this for years with golden-ratio without issue.)

**Comment by idbrii** [comment]
>I've used this for years with golden-ratio without issue.

I'm confused. golden-ratio hasn't updated since 2017. How come this issue is cropping up for you now?

Regardless, I can repro your issue. Even without the mapping, if you `q:`, it occurs.

**Comment by Shurakai** [comment]
Thanks for fixing this, it indeed resolved the issue. I only recently updated my vim (~ 2 years old) and all plugins (probably even older), so that's probably why.

Thanks again!
