### ISSUE TITLE
Unknown function: win_gettype

### ISSUE THREAD

**Issue by JWCook** [roman/golden-ratio#41]
It looks like #40 added a call to `win_gettype()`, which I believe was added to neovim somewhat recently. Maybe 0.6? I couldn't find it in the [release notes](https://github.com/neovim/neovim/releases), but found reference to it in [this commit](https://github.com/neovim/neovim/commit/752ca2cb9f61b4dc523552d4123729b9b26a3409). Anyway, when running an older neovim version, you will get an error like:
```
Unknown function: win_gettype
```
Or possibly:
```
Invalid expression: win_gettype(winnr()) == 'popup'
```

The solution is obviously to update neovim. I'm just adding this issue to make it searchable and potentially save others a few minutes of debugging.

There's nothing the maintainer needs to do here, although mentioning a minimum neovim version in the Readme might be helpful.

**Comment by idbrii** [comment]
Thanks for the informational report!

If someone's motivated, I'd accept a PR adding a check for patch 8.2.0257.
